### PR TITLE
Rename cond ref to capture ref

### PR DESCRIPTION
**Pull request by zherczeg**
I promised this renaming.

### CODE REVIEW

**Comment by zherczeg** [comment]
Btw there is no dnref in any of the test outputs.

**Review by carenas — CHANGES_REQUESTED** [review]
need to also update `pcre2_printint`

**Comment by zherczeg** [comment]
Where? It uses the OP_NAME_LIST from the internal header. The arguments are not changed.

**Comment by PhilipHazel** [comment]
I think he means the phrase "cond ref" in the output should be "capture ref".

**Comment by zherczeg** [comment]
Which output? I am sorry I cannot follow.

**Comment by carenas** [comment]
Sorry; I updated my original comment so it is less vague.

I also think it might be worth adding some tests that exercise it:

```
diff --git a/testdata/testinput2 b/testdata/testinput2
index 9c59bb5..1324b4b 100644
--- a/testdata/testinput2
+++ b/testdata/testinput2
@@ -2862,6 +2862,13 @@
     b"11111
     a"11111
 
+/(?:a(?<digit>[0-5])|b(?<digit>[4-7]))c(?(<digit>)d|e)/B,dupnames
+    a4cd
+    b4cd
+\= Expect no match
+    a6cd
+    a6ce
+
 /^(?|(a)(b)(c)(?<D>d)|(?<D>e)) (?('D')X|Y)/IBx,dupnames
     abcdX
     eX
```

**Comment by zherczeg** [comment]
Thank you for the explanation. I have updated the patch.

**Review by carenas — APPROVED** [review]

**Pull request merged**
