### PR TITLE
jit: replace open coded SSIZE_OF(sw)

### PR DESCRIPTION
**Pull request by carenas**
mostly to silence warnings in Visual Studio, but also making the code more consistent.

### CODE REVIEW

**Review by zherczeg — APPROVED** [review]
LGTM

**Comment by zherczeg** [comment]
Win32 complains about unresolved externals

**Comment by carenas** [comment]
> Win32 complains about unresolved externals

it is the same issue that was fixed by #166

**Review by zherczeg — APPROVED** [review]
LGTM

**Pull request merged**
