### PR TITLE
Add OpenSSF Scorecards to impove the security posture

### PR DESCRIPTION
**Pull request by flyfishzy**
# What is Scorecards?
Scorecards is an [`Open Source Security Fundation`](https://openssf.org/) porject.
> Scorecards is an automated tool that assesses a number of important heuristics [("checks")](https://github.com/ossf/scorecard#scorecard-checks) associated with software security and assigns each check a score of 0-10. You can use these scores to understand specific areas to improve in order to strengthen the security posture of your project.
https://github.com/ossf/scorecard

# Troubleshooting
In order to make Scorecards works correctly,  a `Read-only Access Token` needs to be added to the project.
You can reference https://github.com/ossf/scorecard-action#authentication

### CODE REVIEW

**Comment by zherczeg** [comment]
What is the benefit of this? It seems it gives you numbers which you can compare between projects. I don't have good experiences with such numbers they are often confusing.

**Comment by flyfishzy** [comment]
It can help improve security posture, eg. `Static Application Security Testing (SAST)`,`CI-Tests`,`Branch-Protection` and so on.
This PR add two github actions which are automatically triggered whenever there is a code commit.

**Comment by PhilipHazel** [comment]
I'm pleased to note that running this check found only one issue: a grumble about a potential integer overflow in pcre2test which in practice could never happen. Nevertheless, it is always helpful to have more checking going on, so I have merged this PR. As well as fixing the reported issue, this did get me to add some other small related tidies to pcre2test.

**Comment by PhilipHazel** [comment]
Spoke too soon ... there seems to be a problem with running the workflow.

**Comment by flyfishzy** [comment]
It looks like the scorecards analysis run failed.
In order to make Scorecards works correctly, a Read-only Access Token needs to be added to the project.
You can reference https://github.com/ossf/scorecard-action#authentication

**Comment by PhilipHazel** [comment]
I believe I have sorted this out. The action has run clean.

**Pull request merged**
