### PR TITLE
Revert "Correct spelling mistakes (#143)"

### PR DESCRIPTION
**Pull request by GSS1PRO**
This reverts commit db53e4007db5e1fcfa144ddf10d0499a111a770b.

### CODE REVIEW

**Comment by zherczeg** [comment]
Why?

**Comment by PDowney** [comment]
I can't think of a single reason why anyone would want to revert a commit that fixes a bunch of typos. What a strange PR.

**Comment by PhilipHazel** [comment]
I agree that this is weird. I suppose I can just close it without doing anything else.

**Comment by PhilipHazel** [comment]
Closing because this won't be acted on.

**Pull request closed without merging**
