### PR TITLE
Fuzzer: fix JIT fuzzing

### PR DESCRIPTION
**Pull request by addisoncrump**
This fixes a couple of issues that were discovered after #317 was merged (most importantly, that JIT fuzzing doesn't even happen!).

This shouldn't be merged until we squash the discovered bugs. I'll open those separately and link to this PR.

### CODE REVIEW

**Comment by addisoncrump** [comment]
@PhilipHazel Is there a preferred security reporting process? Haven't found anything too dire, but in the case that something clearly security-relevant comes up it would be good to know what your preference is.

**Comment by PhilipHazel** [comment]
Please post something when you think this is ready for merging. As for security reporting, there isn't any preferred process. I can usually read GPG-encrypted email if you feel that is appropriate. In relation to that, I should point out that I am getting old, and at some point somebody else will have to take over this project.

**Comment by addisoncrump** [comment]
Understood. If it helps, there is a [feature in GitHub that allows for security reporting](https://docs.github.com/en/code-security/security-advisories/guidance-on-reporting-and-writing-information-about-vulnerabilities/privately-reporting-a-security-vulnerability) that might reduce some of the workload and make it easier to transfer later if you decide to hand off the project to someone else.

**Comment by PhilipHazel** [comment]
I am (slowly) working my way through the list of issues you have raised and will fix any non-JIT things, and Zoltan is on the case for JIT so with luck the issues will be resolved. I would like to get a new release out fairly soon as it is almost a year since the last one.

**Comment by addisoncrump** [comment]
Okay. Differential testing tends to uncover a lot of oddities, so I know it's a lot. 

I've not yet reported some things yet, mostly because I want to have a better understanding of the problem before I report them; there's considerable effort involved in reducing testcases to the minimal reproducers and exploring what aspects of the input actually cause the inconsistency/crash. I'm investigating several link size-related issues presently and hope these are simple to resolve (assumption of size and so on).

**Comment by addisoncrump** [comment]
Marking as draft because I want to get MSAN working with JIT.

**Comment by addisoncrump** [comment]
@PhilipHazel, would you look at the changes in OSS-Fuzz and review them as well? :slightly_smiling_face: https://github.com/google/oss-fuzz/pull/11195

**Comment by PhilipHazel** [comment]
Hi,
I've added an OK comment to the oss-fuzz PR, but do I need to do something
else to formally approve? (I have also released 10.43. Now wait for the
bugs to drop out....)
Regards,
Philip

**Pull request merged**
